apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-redis-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /redis
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-redis
                port:
                  number: {{ .Values.service.port }}

